#!/usr/bin/env bash
# mkinitcpio install hook - vhdboot (kloop/vloop/squashfs)
# Copy to chroot /usr/lib/initcpio/install/vhdboot

build() {
    add_binary kpartx
    add_binary partx
    add_binary blkid
    add_binary mount.ntfs-3g
    add_binary ntfs-3g
    add_module fuse
    add_module loop
    add_module dm_mod
    add_module squashfs
    add_module overlay
    add_runscript
}

help() {
    cat <<HELPEOF
Adds support for booting from VHD/VMDK/VDI/QCOW2/VHDX/SquashFS.
  kloop mode: kloop=/path/to.vhd kroot=/dev/mapper/loop0p1
  vloop mode: vloop=/path/to.vhd vlooppart=p1
  squashfs:   squashfs=/path/to/rootfs.squashfs (boots with tmpfs overlay in RAM)
HELPEOF
}
