#!/bin/bash
# Common function library

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REBUILD2_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="${REBUILD2_ROOT}/config/mirrors.conf"

[ -f "$CONFIG" ] && source "$CONFIG"
[ -f "$REBUILD2_ROOT/config/initramfs-defaults.conf" ] && source "$REBUILD2_ROOT/config/initramfs-defaults.conf"

VD_BOOT_VERSION="0.1.0"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
debug() { [ "${VD_DEBUG:-0}" = "1" ] && echo -e "${CYAN}[DEBUG]${NC} $*" || true; }

check_root() {
    [ "$(id -u)" -eq 0 ] || err "Please run this script as root or with sudo"
}

check_deps() {
    local missing=""
    command -v qemu-img >/dev/null 2>&1 || missing="$missing qemu-utils"
    command -v parted   >/dev/null 2>&1 || missing="$missing parted"
    command -v mkfs.ext4 >/dev/null 2>&1 || missing="$missing e2fsprogs"
    command -v kpartx   >/dev/null 2>&1 || missing="$missing kpartx"
    if [ -n "$missing" ]; then
        err "Missing dependencies:$missing\nInstall with: apt install$missing  (Debian/Ubuntu)\n             pacman -S$missing  (Arch)\n             dnf install$missing  (Fedora)"
    fi
}

check_squashfs_deps() {
    local missing=""
    command -v mksquashfs >/dev/null 2>&1 || missing="$missing squashfs-tools"
    if [ -n "$missing" ]; then
        err "Missing SquashFS dependencies:$missing\nInstall with: apt install$missing  (Debian/Ubuntu)\n             pacman -S$missing  (Arch)\n             dnf install$missing  (Fedora)"
    fi
}

cleanup_mount() {
    local mnt="$1"
    [ -n "$mnt" ] && [ -d "$mnt" ] && mountpoint -q "$mnt" && umount -R "$mnt" 2>/dev/null || true
}

# Register cleanup trap for build scripts; call with: setup_cleanup_trap <mnt> <loop_var_name>
# Stores mnt and loop_dev in globals so the trap can reference them
_CLEANUP_MNT=""
_CLEANUP_LOOP=""
_CLEANUP_WORKDIR=""

setup_cleanup_trap() {
    _CLEANUP_MNT="$1"
    _CLEANUP_LOOP="$2"
    _CLEANUP_WORKDIR="$3"
    trap '_cleanup_on_error' EXIT ERR
}

_cleanup_on_error() {
    local rc=$?
    if [ $rc -ne 0 ]; then
        warn "Build failed (exit code $rc), cleaning up..."
        if [ -n "$_CLEANUP_MNT" ]; then
            umount "$_CLEANUP_MNT/run"     2>/dev/null || true
            umount "$_CLEANUP_MNT/dev/pts" 2>/dev/null || true
            umount "$_CLEANUP_MNT/dev"     2>/dev/null || true
            umount "$_CLEANUP_MNT/sys"     2>/dev/null || true
            umount "$_CLEANUP_MNT/proc"    2>/dev/null || true
            umount -R "$_CLEANUP_MNT"      2>/dev/null || true
        fi
        if [ -n "$_CLEANUP_LOOP" ] && [ -b "$_CLEANUP_LOOP" ]; then
            losetup -d "$_CLEANUP_LOOP" 2>/dev/null || true
        fi
    fi
    trap - EXIT ERR
}

clear_cleanup_trap() {
    trap - EXIT ERR
}

# Generate /etc/fstab in the chroot
generate_fstab() {
    local mnt="$1"
    local loop_dev="$2"

    local part="${loop_dev}p1"
    [ -b "$part" ] || part="${loop_dev}1"

    local uuid=""
    uuid=$(blkid -s UUID -o value "$part" 2>/dev/null) || true

    if [ -n "$uuid" ]; then
        cat > "$mnt/etc/fstab" << EOF
# /etc/fstab - generated by vd-boot
UUID=$uuid  /  ext4  defaults,errors=remount-ro  0  1
EOF
    else
        cat > "$mnt/etc/fstab" << EOF
# /etc/fstab - generated by vd-boot
/dev/sda1  /  ext4  defaults,errors=remount-ro  0  1
EOF
    fi
    info "Generated /etc/fstab"
}

# Set root password (default: vdboot)
setup_root_password() {
    local mnt="$1"
    local password="${2:-vdboot}"
    echo "root:${password}" | chroot "$mnt" chpasswd 2>/dev/null || \
    chroot "$mnt" bash -c "echo 'root:${password}' | chpasswd" 2>/dev/null || \
        warn "Failed to set root password"
    info "Root password set (default: $password)"
}

# Configure basic networking (systemd-networkd DHCP)
setup_network() {
    local mnt="$1"

    if [ -d "$mnt/etc/systemd/network" ] || [ -d "$mnt/usr/lib/systemd" ]; then
        mkdir -p "$mnt/etc/systemd/network"
        cat > "$mnt/etc/systemd/network/20-wired.network" << 'EOF'
[Match]
Name=en* eth*

[Network]
DHCP=yes

[DHCPv4]
UseDNS=yes
EOF
        chroot "$mnt" systemctl enable systemd-networkd 2>/dev/null || true
        chroot "$mnt" systemctl enable systemd-resolved 2>/dev/null || true
        info "Configured systemd-networkd (DHCP)"
    fi

    # Fallback: traditional /etc/network/interfaces (Debian/Ubuntu)
    if [ -d "$mnt/etc/network" ]; then
        mkdir -p "$mnt/etc/network"
        cat > "$mnt/etc/network/interfaces" << 'EOF'
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
EOF
        info "Configured /etc/network/interfaces (DHCP)"
    fi

    # DNS fallback
    if [ ! -L "$mnt/etc/resolv.conf" ] || [ ! -f "$mnt/etc/resolv.conf" ]; then
        cat > "$mnt/etc/resolv.conf" << 'EOF'
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF
    fi
}

# Validate value is in allowed list
validate_choice() {
    local value="$1" name="$2"
    shift 2
    local choices="$*"
    for c in $choices; do
        [ "$value" = "$c" ] && return 0
    done
    err "Invalid $name: '$value' (allowed: $choices)"
}
