# Tsinghua University Open Source Software Mirror
# https://mirrors.tuna.tsinghua.edu.cn

MIRROR_ARCH="https://mirrors.tuna.tsinghua.edu.cn/archlinux"
MIRROR_ARCH_ISO="${MIRROR_ARCH}/iso/latest"
MIRROR_ARCH_BOOTSTRAP="${MIRROR_ARCH_ISO}/archlinux-bootstrap-x86_64.tar.zst"

MIRROR_UBUNTU="https://mirrors.tuna.tsinghua.edu.cn/ubuntu"
# noble=24.04, jammy=22.04, focal=20.04
UBUNTU_CODENAME="noble"

MIRROR_FEDORA="https://mirrors.tuna.tsinghua.edu.cn/fedora"
# 41, 40, 39
FEDORA_RELEASE="41"

MIRROR_DEBIAN="https://mirrors.tuna.tsinghua.edu.cn/debian"
# bookworm=12, trixie=13, bullseye=11
DEBIAN_CODENAME="bookworm"

MIRROR_DEEPIN="https://mirrors.tuna.tsinghua.edu.cn/deepin"
# apricot=20.x, beige=23.x
DEEPIN_CODENAME="apricot"

MIRROR_OPENSUSE="https://mirrors.tuna.tsinghua.edu.cn/opensuse"
# 15.6, 15.5
OPENSUSE_LEAP="15.6"
