# mkinitcpio config - vloop mode
# For booting from VHD/VMDK/VDI/QCOW2/VHDX/SquashFS (Arch Linux)

MODULES=(fuse ntfs loop dm-mod squashfs overlay)
BINARIES=(losetup kpartx partx mount.fuse mount.ntfs-3g ntfs-3g shutdown)
FILES=()
HOOKS=(base udev autodetect modconf block keyboard filesystems fsck vhdboot usr shutdown)
