# mkinitcpio config - vloop mode
# For booting from VHD file (Arch Linux)

MODULES=(fuse ntfs loop dm-mod)
BINARIES=(losetup kpartx partx mount.fuse mount.ntfs-3g ntfs-3g shutdown)
FILES=()
HOOKS=(base udev autodetect modconf block keyboard filesystems fsck vhdboot usr shutdown)
