# mkinitcpio config - kloop mode
# For booting from VHD file (Arch Linux)

MODULES=(fuse ntfs loop dm-mod)
BINARIES=(losetup kpartx partx mount.fuse mount.ntfs-3g ntfs-3g shutdown lvm vgscan vgchange)
FILES=()
HOOKS=(base udev autodetect modconf block keyboard filesystems fsck lvm2 mdadm_udev vhdboot usr shutdown)
