# mkinitcpio config - kloop mode
# For booting from VHD/VMDK/VDI/QCOW2/VHDX/SquashFS (Arch Linux)

MODULES=(fuse ntfs loop dm-mod squashfs overlay)
BINARIES=(losetup kpartx partx mount.fuse mount.ntfs-3g ntfs-3g shutdown lvm vgscan vgchange)
FILES=()
HOOKS=(base udev autodetect modconf block keyboard filesystems fsck lvm2 mdadm_udev vhdboot usr shutdown)
